### ISSUE TITLE
Desenvolver a Nossa Gramática

### ISSUE THREAD

**Issue by ghost** [Zanfroni/LingProgT1#4]
Criar e aprimorar uma gramática que reconheça a nossa função escolhida: show

**Comment by ghost** [comment]
Primeira versão pronta: erros ao testar.

**Comment by ghost** [comment]
Descobrir e aprender melhor forma de debbugging para nossa gramática

**Comment by Zanfroni** [comment]
Gramática final desenvolvida e funcional.
